### ISSUE TITLE
No support for string() function

### ISSUE THREAD

**Issue by davidsamlee** [EdgeVerve/feel#34]
The DMN specification includes a string() function to allow conversion from other data types (e.g. numbers) 

When I try to evaluate string(1.1) as a FEEL expression I get 

``TypeError: Cannot read properties of undefined (reading 'fn')
    at processUserDefinedFunction (/home/david/x-rules/node_modules/js-feel/dist/feel-ast-parser.js:358:27)
    at processFnMeta (/home/david/x-rules/node_modules/js-feel/dist/feel-ast-parser.js:397:16)``

Implying the function is not available as a built-in so it looks for it as a user-defined function. 
Please can someone implement this?

**Comment by kvsrohit** [comment]
@deostroll please check.
